import re
import sys
from datetime import datetime

TAB = "    "
# Used for token that can be found on the 7th, column. Like the '*' for comments.
COL7 = "      "
COL8 = "       "

def get_output_generation_header(file_name:str) -> list[str]:
    header:list[str] = []

    header.append(f"{COL7}* Generated by EZCBL from {file_name}")
    header.append(f"{COL7}* DO NOT EDIT - changes will be overwritten")
    header.append(f"{COL7}* Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    return header



def compile_ezcbl(source:str, file_name:str) -> str:
    header = get_output_generation_header(file_name)

    data:list[str] = [f'{COL8}DATA DIVISION.',
                      f'{COL8}WORKING-STORAGE SECTION.']

    procedure:list[str] = [f'{COL8}PROCEDURE DIVISION.',
                           f'',
                           f'{COL8}{TAB}PERFORM 2000-TRAITEMENT-PRINCIPAL',
                           f'',
                           f'{COL8}{TAB}.']
    
    main_process:list[str] = [f'{COL8}2000-TRAITEMENT-PRINCIPAL.']

    paragraphs:list[str] = []


    pattern = r'(\w+)\(([^)]+)\)'

    for match in re.finditer(pattern, source):
        func_name = match.group(1)
        args_str = match.group(2)
        args = [arg.strip() for arg in args_str.split(',')]

        #print(f"Function: {func_name}")
        #print(f"Arguments: {args_str}")
        #print(f"Arguments: {args}")

        data.append(f"{COL8}01 LT-{func_name} PIC X(08) VALUE '{func_name}'.")

        main_process.append(f"{COL8}{TAB}PERFORM CALL-{func_name}")
        paragraphs.append(f"")
        paragraphs.append(f"{COL8}CALL-{func_name}.")

        for arg in args:
            paragraphs.append(f"{COL8}{TAB}MOVE {arg}")
            paragraphs.append(f"{COL8}{TAB}  TO {arg} OF WS-PARAMS")
            paragraphs.append(f"")

        paragraphs.append(f"{COL8}{TAB}CALL LT-{func_name} USING WS-PARAMS")
        paragraphs.append(f"{COL8}{TAB}.")
        paragraphs.append(f"")

    main_process.append(f'{COL8}{TAB}.')
    output:list[str] = []
    output.extend(header)
    output.extend(data)
    output.extend(procedure)
    output.extend(main_process)
    output.extend(paragraphs)

    return '\n'.join(output)

if __name__ == '__main__':
    file_name = sys.argv[1]
    with open(file_name) as f:
        source = f.read()
    output = compile_ezcbl(source, file_name)
    with open('output/output.cbl', mode="w") as f:
        f.write(output)